modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "{{ Mod ID }}"
version = "${version}"
displayName = "{{ Mod Name }}"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.{{ Mod ID }}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{ Mod ID }}]]
modId = "minecraft"
mandatory = true
versionRange = "[{{ MC Version }},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{ Mod ID }}]]
modId = "architectury"
mandatory = true
versionRange = "[{{ Arch API Version }},)"
ordering = "AFTER"
side = "BOTH"
